version: "3.3"

services:
  docky-onion:
    build: .
    restart: always
    environment:
      # this forwards 80 and 8080 to web:80
      TOR_HIDDEN_SERVICE_WEB: "80 web:80;8080 web:80"
    volumes:
      - "docky-onion:/var/lib/tor/hidden_services"
    depends_on:
      - web

  web:
    image: nginx
    restart: always

volumes:
  docky-onion:
